let state={config:null,shop:null,profile:null,tab:'titles',demo:false,me:null,game:'slot'};
const $=q=>document.querySelector(q);
const fmt=n=>Number(n||0).toLocaleString('ko-KR');
const storeKey='natsumi-game-demo';
const gameDefs={slot:{name:'슬롯머신',icon:'🎰',desc:'같은 그림을 맞춰 금전을 노려봐.',api:'/api/games/slot'},fishbun:{name:'붕어빵뽑기',icon:'🥞',desc:'뜨끈뜨끈한 붕어빵 운빨 게임!',api:'/api/games/fishbun'},mine:{name:'비밀 광산',icon:'⛏️',desc:'곡괭이질 한 번에 대박 광맥을 노려.',api:'/api/games/mine'},mole:{name:'두더지 잡기',icon:'🐹',desc:'하트 인증 후 두더지 보상을 정산해.',api:'/api/games/mole'},fishing:{name:'낚시',icon:'🎣',desc:'물고기와 잡동사니를 낚아 금전을 벌어.',api:'/api/games/fishing'}};
const titleNames=['초보 여우','출석 수호자','동전 수집가','새벽의 지배자','랭크 사냥꾼','여우 조련사','행운의 꼬리','MVP','콤보 스타','보스 슬레이어','길드 에이스','금전왕','채팅 전설','불꽃 심장','크리스탈 두뇌','그림자 질주자','여명의 용사','나츠미의 관심대상','신화급 플레이어','영원의 챔피언'];
const badgeNames=['첫 발자국','작은 동전','출석혼','반짝임','여우 발바닥','연승 불꽃','랭크 스파크','달빛 표식','행운 클로버','황금 주머니','핑크 하트','푸른 별','작은 왕관','다이아 조각','검의 문장','방패 문장','용의 비늘','은하 코어','서포터','전설 인증'];
const tEmoji=['🦊','📅','🪙','🌙','🎯','🦊','🍀','🏆','🌟','⚔️','🛡️','💰','💬','🔥','💎','🥷','🌅','😼','🐉','👑'];
const bEmoji=['🐾','🪙','📅','✨','🐾','🔥','⚡','🌙','🍀','👝','💗','🔷','👑','💎','🗡️','🛡️','🐉','🌌','💖','🏅'];
const demoShop={titles:titleNames.map((name,i)=>({key:i===7?'mvp':'title_'+i,name,description:`${name} 칭호`,price:50000+i*35000,emoji:tEmoji[i]})),badges:badgeNames.map((name,i)=>({key:i===18?'supporter':'badge_'+i,name,description:`${name} 뱃지`,price:50000+i*30000,emoji:bEmoji[i]}))};
function getConfig(){const c=window.NATSUMI_CONFIG||{};return{apiBase:(c.API_BASE||'').replace(/\/$/,''),defaultGuildId:c.DEFAULT_GUILD_ID||'',donationUrl:c.DONATION_URL||'',donationEnabled:Boolean(c.DONATION_URL)}}
function readAll(){try{return JSON.parse(localStorage.getItem(storeKey)||'{}')}catch{return {}}}
function writeAll(v){localStorage.setItem(storeKey,JSON.stringify(v))}
function getInv(id){const all=readAll();if(!all[id])all[id]={money:300000,titles:['title_0'],badges:['badge_0'],activeTitle:'title_0'};writeAll(all);return all[id]}
function saveInv(id,inv){const all=readAll();all[id]=inv;writeAll(all)}
async function api(url,options){if(!state.config?.apiBase)throw new Error('NO_API');const res=await fetch(`${state.config.apiBase}${url}`,{credentials:'include',headers:{'content-type':'application/json'},...options});const data=await res.json();if(!res.ok)throw Object.assign(new Error(data.error||'요청 실패'),{data});return data}
function currentUserId(){return state.me?.id||(state.config?.apiBase?'':'demo-user')}
function rankUrl(guildId,id){return state.config.apiBase?`${state.config.apiBase}/rank-card/${guildId}/${id}`:'#rankView'}
function demoProfile(guildId,id){const inv=getInv(id);const level=12,xp=4750,needed=level*level*100;return{guildId,userId:id,level,xp,needed,progress:Math.round(xp/needed*1000)/10,money:inv.money,attendance:27,activeTitle:inv.activeTitle,ownedTitles:demoShop.titles.filter(t=>inv.titles.includes(t.key)),ownedBadges:demoShop.badges.filter(b=>inv.badges.includes(b.key))}}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(`#${name}View`)?.classList.add('active-view');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function itemCard(item,type){return `<article class="item"><div class="emoji">${item.emoji}</div><h3>${item.name}</h3><small>${item.description}</small><p><b>${fmt(item.price)}</b> 금전</p><button data-buy="${type}" data-key="${item.key}">구매하기</button></article>`}
function renderShop(){if(!state.shop)return;const list=state.tab==='titles'?state.shop.titles:state.shop.badges;$('#shopArea').innerHTML=list.map(x=>itemCard(x,state.tab==='titles'?'title':'badge')).join('');document.querySelectorAll('[data-buy]').forEach(btn=>btn.addEventListener('click',buyItem))}
function renderGames(){const area=$('#gameList');if(!area)return;area.innerHTML=Object.entries(gameDefs).map(([key,g])=>`<button class="game-choice ${state.game===key?'active':''}" data-game="${key}"><span class="game-icon">${g.icon}</span><span><b>${g.name}</b><br><small>${g.desc}</small></span></button>`).join('');document.querySelectorAll('[data-game]').forEach(btn=>btn.addEventListener('click',()=>selectGame(btn.dataset.game)));selectGame(state.game)}
function selectGame(key){state.game=key;const g=gameDefs[key];document.querySelectorAll('[data-game]').forEach(btn=>btn.classList.toggle('active',btn.dataset.game===key));$('#gameArt').textContent=g.icon;$('#gameTitle').textContent=g.name;$('#gameDesc').textContent=g.desc;$('#betInput').style.display=key==='fishing'?'none':'block'}
function renderProfile(){const p=state.profile;if(!p)return;const active=p.ownedTitles.find(t=>t.key===p.activeTitle);const titleOptions=p.ownedTitles.length?p.ownedTitles.map(t=>`<button class="tab" data-title="${t.key}">${t.emoji} ${t.name}</button>`).join(''):'<p>보유 칭호 없음</p>';const badges=p.ownedBadges.length?p.ownedBadges.map(b=>`<span title="${b.name}">${b.emoji}</span>`).join(' '):'뱃지 없음';$('#profileArea').className='rank-card';$('#profileArea').innerHTML=`<div class="rank-glow"></div><div><p class="eyebrow">${active?`${active.emoji} ${active.name}`:'🦊 NATSUMI PLAYER'} ${state.demo?'· DEMO':''}</p><h1>${state.me?.globalName||state.me?.username||p.userId}</h1><p>${badges}</p></div><div class="level-badge">Lv.${p.level}</div><div class="stats"><div class="stat"><span>영력</span><b>${fmt(p.xp)} / ${fmt(p.needed)}</b></div><div class="stat"><span>금전</span><b>${fmt(p.money)}</b></div><div class="stat"><span>출석</span><b>${fmt(p.attendance)}회</b></div></div><div class="progress"><span style="width:${p.progress}%"></span></div><p>진행률 ${p.progress}% · <a target="_blank" href="${rankUrl(p.guildId,p.userId)}">웹 랭크카드 열기</a></p><h3>활성 칭호 선택</h3><div class="shop-tabs">${titleOptions}</div>`;$('#rankCardLink').href=rankUrl(p.guildId,p.userId);document.querySelectorAll('[data-title]').forEach(btn=>btn.addEventListener('click',selectTitle))}
async function loadMe(){try{const me=await api('/api/me');state.me=me.user||null}catch{state.me=null}if(state.me){$('#loginName').textContent=`${state.me.globalName||state.me.username}님`;$('#loginBtn').classList.add('hidden');$('#logoutBtn').classList.remove('hidden')}else{$('#loginName').textContent='게스트 모드';$('#loginBtn').classList.remove('hidden')}}
async function loadProfile(){const guildId=state.config.defaultGuildId||'demo-guild';const id=currentUserId();if(!id){alert('Discord 로그인이 필요해.');return}try{state.profile=await api(`/api/profile/${guildId}/${id}`);state.demo=false}catch{state.profile=demoProfile(guildId,id);state.demo=true}renderProfile();renderShop()}
async function buyItem(e){const id=currentUserId();if(!id){alert('Discord 로그인이 필요해.');return}const itemType=e.currentTarget.dataset.buy,key=e.currentTarget.dataset.key;try{const data=await api('/api/buy',{method:'POST',body:JSON.stringify({itemType,key})});alert(data.message);await loadProfile()}catch{const list=itemType==='title'?demoShop.titles:demoShop.badges,item=list.find(x=>x.key===key),inv=getInv(id),field=itemType==='title'?'titles':'badges';if(inv[field].includes(key)){alert('이미 가지고 있는 아이템이야.');return}if(inv.money<item.price){alert(`금전 부족! 필요 ${fmt(item.price)}, 보유 ${fmt(inv.money)}`);return}inv.money-=item.price;inv[field].push(key);if(itemType==='title'&&!inv.activeTitle)inv.activeTitle=key;saveInv(id,inv);alert(`${item.emoji} ${item.name} 데모 구매 완료!`);await loadProfile()}}
async function selectTitle(e){const id=currentUserId(),key=e.currentTarget.dataset.title;if(!id){alert('Discord 로그인이 필요해.');return}try{await api('/api/title/select',{method:'POST',body:JSON.stringify({key})})}catch{const inv=getInv(id);if(!inv.titles.includes(key)){alert('보유하지 않은 칭호야.');return}inv.activeTitle=key;saveInv(id,inv)}await loadProfile()}
async function playGame(){const id=currentUserId();if(!id){alert('Discord 로그인 후 이용해줘.');return}const key=state.game,g=gameDefs[key],bet=Number($('#betInput').value||1000);$('#gameResult').textContent='나츠미가 결과를 굴리는 중... 🦊';try{const data=await api(g.api,{method:'POST',body:JSON.stringify({bet,score:key==='mole'?Math.floor(Math.random()*80)+20:undefined,difficulty:'medium'})});$('#gameResult').textContent=formatGameResult(data);await loadProfile()}catch(err){if(err?.data?.heartRequired){$('#gameResult').innerHTML=`한디리 하트를 눌러야 게임 가능!\n<a class="primary-link" target="_blank" href="${err.data.heartUrl}">하트 누르기</a>`;return}const inv=getInv(id),delta=demoGameDelta(key,bet);inv.money=Math.max(0,inv.money+delta);saveInv(id,inv);$('#gameResult').textContent=`${g.icon} ${g.name} 데모 결과\n변동 금전: ${delta>=0?'+':''}${fmt(delta)}\n현재 금전: ${fmt(inv.money)}`;await loadProfile()}}
function formatGameResult(d){if(d.reels)return `${d.reels.join(' | ')}\n결과: ${d.result}\n변동 금전: ${d.delta>=0?'+':''}${fmt(d.delta)}\n현재 금전: ${fmt(d.money)}`;return `${d.item||d.game}\n변동 금전: ${d.delta>=0?'+':''}${fmt(d.delta)}\n현재 금전: ${fmt(d.money)}`}
function demoGameDelta(key,bet){if(key==='fishing')return 800;if(key==='mole')return 12000;const r=Math.random();if(r>.75)return Math.floor(bet*3);if(r>.45)return Math.floor(bet*1.2);return -bet}
async function logout(){try{await api('/auth/logout',{method:'POST',body:'{}'})}catch{}location.reload()}
async function init(){state.config=getConfig();if(state.config.donationEnabled){$('#donateLink').href=state.config.donationUrl;$('#donateLink').classList.remove('hidden')}await loadMe();try{state.shop=await api('/api/shop')}catch{state.shop=demoShop;state.demo=true}renderShop();renderGames();if(state.me)await loadProfile();$('#loadBtn').addEventListener('click',loadProfile);$('#playGameBtn').addEventListener('click',playGame);$('#logoutBtn').addEventListener('click',logout);document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));document.querySelectorAll('.tab[data-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab[data-tab]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.tab=btn.dataset.tab;renderShop()}))}
init().catch(err=>{console.error(err);alert('초기화 실패: '+err.message)});
